# Generated by Django 3.2.12 on 2024-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_repair_computer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='status',
            field=models.CharField(choices=[('WORKING', 'Working'), ('NOT WORKING', 'Not Working'), ('TRASHED', 'Trashed')], default='WORKING', max_length=20),
        ),
    ]
