# Generated by Django 4.2.1 on 2024-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_computers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
