# Generated by Django 4.2.13 on 2024-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_lab_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='status',
            field=models.CharField(choices=[('working', 'working'), ('not working', 'not working'), ('TRASHED', 'Trashed')], default='working', max_length=20),
        ),
    ]
