# Generated by Django 4.2.13 on 2024-07-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_computers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram_type',
            name='make',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ram_type',
            name='ram_size',
            field=models.CharField(max_length=25),
        ),
    ]
