# Generated by Django 5.0.2 on 2024-06-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_alter_computers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_details', models.CharField(max_length=50)),
                ('complaint_date', models.DateField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_complaints', to='status.computers')),
            ],
        ),
    ]
