# Generated by Django 4.2.13 on 2024-07-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_alter_ram_type_make_alter_ram_type_ram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='invoice_no',
            field=models.CharField(max_length=20),
        ),
    ]
