# Generated by Django 5.0.2 on 2024-06-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='computer',
        ),
    ]
