# Generated by Django 5.0.6 on 2024-06-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0007_alter_computers_keyboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computers",
            name="keyboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="status.keyboard",
            ),
        ),
    ]
