# Generated by Django 5.0.6 on 2024-06-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0009_rename_c_id_repair_computer_complaint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="status",
        ),
    ]
